package pixelbattle.game;

public enum ItemType {
    DIRT_BLOCK, GRASS_BLOCK, STONE_BLOCK, IRON_ORE, GOLD_ORE, DIAMOND, WOOD, LEAVES,
    IRON_INGOT, GOLD_INGOT,
    WOODEN_PICKAXE, IRON_PICKAXE, GOLD_PICKAXE, DIAMOND_PICKAXE,
    WOODEN_AXE, IRON_AXE, GOLD_AXE, DIAMOND_AXE,
    WOODEN_SWORD, IRON_SWORD, LASER_SWORD,
    BOW, ARROW, GRAPPLING_HOOK, SHIELD,
    HEALTH_POTION, STRENGTH_POTION, SPEED_POTION, SHIELD_POTION,
    WORKBENCH, FURNACE, CIRCUIT_BOARD, ENERGY_CORE,
    SPACESHIP, ROBOT, LASER_GUN, STRING, BULLET
}
